server:
  port: 8081

spring:
  sql:
    init:
      mode: always
  application:
    name: business-service
  datasource:
    shard0:
      jdbc-url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/business_service_db_1}"
      username: ${SPRING_DATASOURCE_USERNAME:neil}
      password: ${SPRING_DATASOURCE_PASSWORD:pass}
      driver-class-name: org.postgresql.Driver
    shard1:
      jdbc-url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/business_service_db_2}"
      username: ${SPRING_DATASOURCE_USERNAME:neil}
      password: ${SPRING_DATASOURCE_PASSWORD:pass}
      driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
#    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG